name: Build and Publish

on:
  push:
    branches: [main, release]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        
    - name: Install Poetry
      run: pip install poetry==1.7.1

    - name: Check out the code
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: poetry install

    - name: Run unit tests
      run: poetry run python -m unittest discover -s tests

    - name: Build the wheel
      run: poetry build

    - name: Configure PyPI token
      if: github.ref == 'refs/heads/release'
      run: poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}  

    - name: Publish to PyPI for Release Branch
      if: github.ref == 'refs/heads/release'
      env:
        POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_API_TOKEN }}
      run: poetry publish --build
    
    - name: Build for main Branch   
      if: github.ref == 'refs/heads/main'
      run: poetry build